# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:16-alpine AS builder

# Install necessary build tools
RUN apk add --no-cache git

# Set working directory
WORKDIR /app

# Copy source files and package.json
COPY package.json tsconfig.json ./
COPY src ./src

# Install dependencies
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

FROM node:16-alpine AS release

# Set working directory
WORKDIR /app

# Copy only necessary files from the builder
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Environment variables (these should be configured as per your project settings)
ENV SUPABASE_URL=your_project_url_here
ENV SUPABASE_KEY=your_service_role_key_here
ENV SUPABASE_ACCESS_TOKEN=your_access_token_here

# Set the entry point for the container
ENTRYPOINT ["node", "build/index.js"]
